import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    backgroundColor: "lightgray",
    padding: 10,
    paddingTop: 40,
    flex: 1,
  },
  canvas: {
    borderWidth: 1,
    borderColor: "black",
    marginTop: 10,
    width: "100%",
    height: 250,
    backgroundColor: "white",
    zIndex: 100,
    position: "relative",
    overflow: "hidden",
  },
  canvasView: {
    position: "absolute",
    padding: 10,
    backgroundColor: "transparent",
    borderRadius: 5,
    margin: 5,
    maxWidth: "100%",
    maxHeight: "100%",
  },
  canvasViewText: {
    fontSize: 25,
    color: "black",
    fontWeight: "bold",
    flexWrap: "wrap",
    maxWidth: "100%",
  },
  viewButton: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 10,
  },
  viewTemplate: {
    width: "100%",
    marginBottom: 10,
  },
  buttonAddImage: {
    width: "50%",
    height: 50,
    backgroundColor: "green",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  buttonAddText: {
    width: "47%",
    height: 50,
    backgroundColor: "orange",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  buttonExportImage: {
    width: "100%",
    height: 50,
    backgroundColor: "red",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  textViewTemplate: { fontSize: 16, fontWeight: "bold" },
  textaAdd: { color: "white", fontSize: 16, fontWeight: "bold" },
  imageTemplate: {
    width: "100%",
    height: "100%",
  },
  buttonTemplate: {
    marginTop: 10,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 5,
  },
  imageTemplateBorder: { width: 80, height: 80, borderRadius: 5 },
});
